<?php

declare(strict_types=1);

namespace Elements\Element;

use DomainException;
use Elements\Category\FlowContentInterface;
use Elements\Category\PalpableContentInterface;
use Elements\NestedElement;
use Elements\Node;

/**
 * Class Dl
 *
 * @package Elements\Element
 */
class Dl extends NestedElement implements FlowContentInterface, PalpableContentInterface
{
    private const TAG = 'dl';

    public function __construct()
    {
        parent::__construct(self::TAG);
    }

    /**
     * @param \Elements\Node $node
     *
     * @throws \DomainException
     */
    public function appendNode(Node $node): void
    {
        if (!($node instanceof Dd) && !($node instanceof Dt) && !($node instanceof Div)) {
            throw new DomainException('');
        }

        parent::appendNode($node); // TODO: Change the autogenerated stub
    }
}
