<?php

declare(strict_types=1);

namespace Elements\Element;

use DomainException;
use Elements\Category\FlowContentInterface;
use Elements\NestedElement;
use Elements\Node;

/**
 * Class Dt
 *
 * @package Elements\Element
 */
class Dt extends NestedElement
{
    private const TAG = 'dt';

    public function __construct()
    {
        parent::__construct(self::TAG);
    }

    /**
     * @param \Elements\Node $node
     *
     * @throws \DomainException
     */
    public function appendNode(Node $node): void
    {
        if (!($node instanceof FlowContentInterface)) {
            throw new DomainException('');
        }

        parent::appendNode($node); // TODO: Change the autogenerated stub
    }
}
