<?php

declare(strict_types=1);

namespace Elements\Core;

/**
 * @package Elements\Architecture
 */
abstract class PHPNode extends NodeContainer
{
    /**
     * @param \Elements\Core\Node $node
     */
    protected function appendNode(Node $node): void
    {
        parent::appendNode($node); // TODO: Change the autogenerated stub
    }
}
